# Generated by Django 3.1.3 on 2020-11-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_slugtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slugTitle',
        ),
    ]
